version: "3.7"
services:
  storybook:
    image: node
    volumes:
      - "./storybook:/mnt/storybook"
    working_dir: "/mnt/storybook"
    entrypoint: "/bin/bash -c"
    command:
      - |
        npm run storybook
    ports:
      - 6006:6006
    
  http-server:
    build:
      context: "./http-server"
    volumes:
      - "./public:/mnt/public"
    working_dir: "/mnt/public"
    entrypoint: "/bin/bash -c"
    command:
      - |
        http-server
    ports:
      - "8080:8080"